name: Gold Price Bot

on:
  schedule:
    - cron: "7 4 * * *"
  workflow_dispatch:

jobs:
  send-gold-price:
    runs-on: ubuntu-latest
    steps:
      - name: Repository'ni yuklab olish
        uses: actions/checkout@v4

      - name: Python o'rnatish
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Kerakli kutubxonani o'rnatish
        run: pip install requests pillow

      - name: Kirill shriftini o'rnatish
        run: sudo apt-get update && sudo apt-get install -y fonts-dejavu-core

      - name: Botni ishga tushirish
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python oltin_narxi_bot.py
